//    Copyright 2019 Google Inc.
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        https://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// @generated by protoc-gen-es v1.4.1 with parameter "target=ts"
// @generated from file proto/google/fhir/proto/r4/core/resources/enrollment_response.proto (package google.fhir.r4.core, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Any, Message, proto3 } from "@bufbuild/protobuf";
import { Code, DateTime, Extension, Id, Identifier, Meta, Narrative, Reference, String, Uri } from "../datatypes_pb.js";
import { ClaimProcessingCode_Value, FinancialResourceStatusCode_Value } from "../codes_pb.js";

/**
 * Auto-generated from StructureDefinition for EnrollmentResponse.
 * EnrollmentResponse resource.
 * See http://hl7.org/fhir/StructureDefinition/EnrollmentResponse
 *
 * @generated from message google.fhir.r4.core.EnrollmentResponse
 */
export class EnrollmentResponse extends Message<EnrollmentResponse> {
  /**
   * Logical id of this artifact
   *
   * @generated from field: google.fhir.r4.core.Id id = 1;
   */
  id?: Id;

  /**
   * Metadata about the resource
   *
   * @generated from field: google.fhir.r4.core.Meta meta = 2;
   */
  meta?: Meta;

  /**
   * A set of rules under which this content was created
   *
   * @generated from field: google.fhir.r4.core.Uri implicit_rules = 3;
   */
  implicitRules?: Uri;

  /**
   * Language of the resource content
   *
   * @generated from field: google.fhir.r4.core.Code language = 4;
   */
  language?: Code;

  /**
   * Text summary of the resource, for human interpretation
   *
   * @generated from field: google.fhir.r4.core.Narrative text = 5;
   */
  text?: Narrative;

  /**
   * Contained, inline Resources
   *
   * @generated from field: repeated google.protobuf.Any contained = 6;
   */
  contained: Any[] = [];

  /**
   * Additional content defined by implementations
   *
   * @generated from field: repeated google.fhir.r4.core.Extension extension = 8;
   */
  extension: Extension[] = [];

  /**
   * Extensions that cannot be ignored
   *
   * @generated from field: repeated google.fhir.r4.core.Extension modifier_extension = 9;
   */
  modifierExtension: Extension[] = [];

  /**
   * Business Identifier
   *
   * @generated from field: repeated google.fhir.r4.core.Identifier identifier = 10;
   */
  identifier: Identifier[] = [];

  /**
   * @generated from field: google.fhir.r4.core.EnrollmentResponse.StatusCode status = 11;
   */
  status?: EnrollmentResponse_StatusCode;

  /**
   * Claim reference
   *
   * @generated from field: google.fhir.r4.core.Reference request = 12;
   */
  request?: Reference;

  /**
   * @generated from field: google.fhir.r4.core.EnrollmentResponse.OutcomeCode outcome = 13;
   */
  outcome?: EnrollmentResponse_OutcomeCode;

  /**
   * Disposition Message
   *
   * @generated from field: google.fhir.r4.core.String disposition = 14;
   */
  disposition?: String;

  /**
   * Creation date
   *
   * @generated from field: google.fhir.r4.core.DateTime created = 15;
   */
  created?: DateTime;

  /**
   * Insurer
   *
   * @generated from field: google.fhir.r4.core.Reference organization = 16;
   */
  organization?: Reference;

  /**
   * Responsible practitioner
   *
   * @generated from field: google.fhir.r4.core.Reference request_provider = 17;
   */
  requestProvider?: Reference;

  constructor(data?: PartialMessage<EnrollmentResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.fhir.r4.core.EnrollmentResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: Id },
    { no: 2, name: "meta", kind: "message", T: Meta },
    { no: 3, name: "implicit_rules", kind: "message", T: Uri },
    { no: 4, name: "language", kind: "message", T: Code },
    { no: 5, name: "text", kind: "message", T: Narrative },
    { no: 6, name: "contained", kind: "message", T: Any, repeated: true },
    { no: 8, name: "extension", kind: "message", T: Extension, repeated: true },
    { no: 9, name: "modifier_extension", kind: "message", T: Extension, repeated: true },
    { no: 10, name: "identifier", kind: "message", T: Identifier, repeated: true },
    { no: 11, name: "status", kind: "message", T: EnrollmentResponse_StatusCode },
    { no: 12, name: "request", kind: "message", T: Reference },
    { no: 13, name: "outcome", kind: "message", T: EnrollmentResponse_OutcomeCode },
    { no: 14, name: "disposition", kind: "message", T: String },
    { no: 15, name: "created", kind: "message", T: DateTime },
    { no: 16, name: "organization", kind: "message", T: Reference },
    { no: 17, name: "request_provider", kind: "message", T: Reference },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EnrollmentResponse {
    return new EnrollmentResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EnrollmentResponse {
    return new EnrollmentResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EnrollmentResponse {
    return new EnrollmentResponse().fromJsonString(jsonString, options);
  }

  static equals(a: EnrollmentResponse | PlainMessage<EnrollmentResponse> | undefined, b: EnrollmentResponse | PlainMessage<EnrollmentResponse> | undefined): boolean {
    return proto3.util.equals(EnrollmentResponse, a, b);
  }
}

/**
 * active | cancelled | draft | entered-in-error
 *
 * @generated from message google.fhir.r4.core.EnrollmentResponse.StatusCode
 */
export class EnrollmentResponse_StatusCode extends Message<EnrollmentResponse_StatusCode> {
  /**
   * @generated from field: google.fhir.r4.core.FinancialResourceStatusCode.Value value = 1;
   */
  value = FinancialResourceStatusCode_Value.INVALID_UNINITIALIZED;

  /**
   * @generated from field: google.fhir.r4.core.String id = 2;
   */
  id?: String;

  /**
   * @generated from field: repeated google.fhir.r4.core.Extension extension = 3;
   */
  extension: Extension[] = [];

  constructor(data?: PartialMessage<EnrollmentResponse_StatusCode>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.fhir.r4.core.EnrollmentResponse.StatusCode";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "value", kind: "enum", T: proto3.getEnumType(FinancialResourceStatusCode_Value) },
    { no: 2, name: "id", kind: "message", T: String },
    { no: 3, name: "extension", kind: "message", T: Extension, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EnrollmentResponse_StatusCode {
    return new EnrollmentResponse_StatusCode().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EnrollmentResponse_StatusCode {
    return new EnrollmentResponse_StatusCode().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EnrollmentResponse_StatusCode {
    return new EnrollmentResponse_StatusCode().fromJsonString(jsonString, options);
  }

  static equals(a: EnrollmentResponse_StatusCode | PlainMessage<EnrollmentResponse_StatusCode> | undefined, b: EnrollmentResponse_StatusCode | PlainMessage<EnrollmentResponse_StatusCode> | undefined): boolean {
    return proto3.util.equals(EnrollmentResponse_StatusCode, a, b);
  }
}

/**
 * queued | complete | error | partial
 *
 * @generated from message google.fhir.r4.core.EnrollmentResponse.OutcomeCode
 */
export class EnrollmentResponse_OutcomeCode extends Message<EnrollmentResponse_OutcomeCode> {
  /**
   * @generated from field: google.fhir.r4.core.ClaimProcessingCode.Value value = 1;
   */
  value = ClaimProcessingCode_Value.INVALID_UNINITIALIZED;

  /**
   * @generated from field: google.fhir.r4.core.String id = 2;
   */
  id?: String;

  /**
   * @generated from field: repeated google.fhir.r4.core.Extension extension = 3;
   */
  extension: Extension[] = [];

  constructor(data?: PartialMessage<EnrollmentResponse_OutcomeCode>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.fhir.r4.core.EnrollmentResponse.OutcomeCode";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "value", kind: "enum", T: proto3.getEnumType(ClaimProcessingCode_Value) },
    { no: 2, name: "id", kind: "message", T: String },
    { no: 3, name: "extension", kind: "message", T: Extension, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EnrollmentResponse_OutcomeCode {
    return new EnrollmentResponse_OutcomeCode().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EnrollmentResponse_OutcomeCode {
    return new EnrollmentResponse_OutcomeCode().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EnrollmentResponse_OutcomeCode {
    return new EnrollmentResponse_OutcomeCode().fromJsonString(jsonString, options);
  }

  static equals(a: EnrollmentResponse_OutcomeCode | PlainMessage<EnrollmentResponse_OutcomeCode> | undefined, b: EnrollmentResponse_OutcomeCode | PlainMessage<EnrollmentResponse_OutcomeCode> | undefined): boolean {
    return proto3.util.equals(EnrollmentResponse_OutcomeCode, a, b);
  }
}

