//    Copyright 2019 Google Inc.
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        https://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// @generated by protoc-gen-es v1.4.1 with parameter "target=ts"
// @generated from file proto/google/fhir/proto/r4/core/resources/invoice.proto (package google.fhir.r4.core, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Any, Message, proto3 } from "@bufbuild/protobuf";
import { Annotation, Code, CodeableConcept, DateTime, Decimal, Extension, Id, Identifier, Markdown, Meta, Money, Narrative, PositiveInt, Reference, String, Uri } from "../datatypes_pb.js";
import { InvoicePriceComponentTypeCode_Value, InvoiceStatusCode_Value } from "../codes_pb.js";

/**
 * Auto-generated from StructureDefinition for Invoice.
 * Invoice containing ChargeItems from an Account.
 * See http://hl7.org/fhir/StructureDefinition/Invoice
 *
 * @generated from message google.fhir.r4.core.Invoice
 */
export class Invoice extends Message<Invoice> {
  /**
   * Logical id of this artifact
   *
   * @generated from field: google.fhir.r4.core.Id id = 1;
   */
  id?: Id;

  /**
   * Metadata about the resource
   *
   * @generated from field: google.fhir.r4.core.Meta meta = 2;
   */
  meta?: Meta;

  /**
   * A set of rules under which this content was created
   *
   * @generated from field: google.fhir.r4.core.Uri implicit_rules = 3;
   */
  implicitRules?: Uri;

  /**
   * Language of the resource content
   *
   * @generated from field: google.fhir.r4.core.Code language = 4;
   */
  language?: Code;

  /**
   * Text summary of the resource, for human interpretation
   *
   * @generated from field: google.fhir.r4.core.Narrative text = 5;
   */
  text?: Narrative;

  /**
   * Contained, inline Resources
   *
   * @generated from field: repeated google.protobuf.Any contained = 6;
   */
  contained: Any[] = [];

  /**
   * Additional content defined by implementations
   *
   * @generated from field: repeated google.fhir.r4.core.Extension extension = 8;
   */
  extension: Extension[] = [];

  /**
   * Extensions that cannot be ignored
   *
   * @generated from field: repeated google.fhir.r4.core.Extension modifier_extension = 9;
   */
  modifierExtension: Extension[] = [];

  /**
   * Business Identifier for item
   *
   * @generated from field: repeated google.fhir.r4.core.Identifier identifier = 10;
   */
  identifier: Identifier[] = [];

  /**
   * @generated from field: google.fhir.r4.core.Invoice.StatusCode status = 11;
   */
  status?: Invoice_StatusCode;

  /**
   * Reason for cancellation of this Invoice
   *
   * @generated from field: google.fhir.r4.core.String cancelled_reason = 12;
   */
  cancelledReason?: String;

  /**
   * Type of Invoice
   *
   * @generated from field: google.fhir.r4.core.CodeableConcept type = 13;
   */
  type?: CodeableConcept;

  /**
   * Recipient(s) of goods and services
   *
   * @generated from field: google.fhir.r4.core.Reference subject = 14;
   */
  subject?: Reference;

  /**
   * Recipient of this invoice
   *
   * @generated from field: google.fhir.r4.core.Reference recipient = 15;
   */
  recipient?: Reference;

  /**
   * Invoice date / posting date
   *
   * @generated from field: google.fhir.r4.core.DateTime date = 16;
   */
  date?: DateTime;

  /**
   * @generated from field: repeated google.fhir.r4.core.Invoice.Participant participant = 17;
   */
  participant: Invoice_Participant[] = [];

  /**
   * Issuing Organization of Invoice
   *
   * @generated from field: google.fhir.r4.core.Reference issuer = 18;
   */
  issuer?: Reference;

  /**
   * Account that is being balanced
   *
   * @generated from field: google.fhir.r4.core.Reference account = 19;
   */
  account?: Reference;

  /**
   * @generated from field: repeated google.fhir.r4.core.Invoice.LineItem line_item = 20;
   */
  lineItem: Invoice_LineItem[] = [];

  /**
   * Components of Invoice total
   *
   * @generated from field: repeated google.fhir.r4.core.Invoice.LineItem.PriceComponent total_price_component = 21;
   */
  totalPriceComponent: Invoice_LineItem_PriceComponent[] = [];

  /**
   * Net total of this Invoice
   *
   * @generated from field: google.fhir.r4.core.Money total_net = 22;
   */
  totalNet?: Money;

  /**
   * Gross total of this Invoice
   *
   * @generated from field: google.fhir.r4.core.Money total_gross = 23;
   */
  totalGross?: Money;

  /**
   * Payment details
   *
   * @generated from field: google.fhir.r4.core.Markdown payment_terms = 24;
   */
  paymentTerms?: Markdown;

  /**
   * Comments made about the invoice
   *
   * @generated from field: repeated google.fhir.r4.core.Annotation note = 25;
   */
  note: Annotation[] = [];

  constructor(data?: PartialMessage<Invoice>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.fhir.r4.core.Invoice";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: Id },
    { no: 2, name: "meta", kind: "message", T: Meta },
    { no: 3, name: "implicit_rules", kind: "message", T: Uri },
    { no: 4, name: "language", kind: "message", T: Code },
    { no: 5, name: "text", kind: "message", T: Narrative },
    { no: 6, name: "contained", kind: "message", T: Any, repeated: true },
    { no: 8, name: "extension", kind: "message", T: Extension, repeated: true },
    { no: 9, name: "modifier_extension", kind: "message", T: Extension, repeated: true },
    { no: 10, name: "identifier", kind: "message", T: Identifier, repeated: true },
    { no: 11, name: "status", kind: "message", T: Invoice_StatusCode },
    { no: 12, name: "cancelled_reason", kind: "message", T: String },
    { no: 13, name: "type", kind: "message", T: CodeableConcept },
    { no: 14, name: "subject", kind: "message", T: Reference },
    { no: 15, name: "recipient", kind: "message", T: Reference },
    { no: 16, name: "date", kind: "message", T: DateTime },
    { no: 17, name: "participant", kind: "message", T: Invoice_Participant, repeated: true },
    { no: 18, name: "issuer", kind: "message", T: Reference },
    { no: 19, name: "account", kind: "message", T: Reference },
    { no: 20, name: "line_item", kind: "message", T: Invoice_LineItem, repeated: true },
    { no: 21, name: "total_price_component", kind: "message", T: Invoice_LineItem_PriceComponent, repeated: true },
    { no: 22, name: "total_net", kind: "message", T: Money },
    { no: 23, name: "total_gross", kind: "message", T: Money },
    { no: 24, name: "payment_terms", kind: "message", T: Markdown },
    { no: 25, name: "note", kind: "message", T: Annotation, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Invoice {
    return new Invoice().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Invoice {
    return new Invoice().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Invoice {
    return new Invoice().fromJsonString(jsonString, options);
  }

  static equals(a: Invoice | PlainMessage<Invoice> | undefined, b: Invoice | PlainMessage<Invoice> | undefined): boolean {
    return proto3.util.equals(Invoice, a, b);
  }
}

/**
 * draft | issued | balanced | cancelled | entered-in-error
 *
 * @generated from message google.fhir.r4.core.Invoice.StatusCode
 */
export class Invoice_StatusCode extends Message<Invoice_StatusCode> {
  /**
   * @generated from field: google.fhir.r4.core.InvoiceStatusCode.Value value = 1;
   */
  value = InvoiceStatusCode_Value.INVALID_UNINITIALIZED;

  /**
   * @generated from field: google.fhir.r4.core.String id = 2;
   */
  id?: String;

  /**
   * @generated from field: repeated google.fhir.r4.core.Extension extension = 3;
   */
  extension: Extension[] = [];

  constructor(data?: PartialMessage<Invoice_StatusCode>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.fhir.r4.core.Invoice.StatusCode";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "value", kind: "enum", T: proto3.getEnumType(InvoiceStatusCode_Value) },
    { no: 2, name: "id", kind: "message", T: String },
    { no: 3, name: "extension", kind: "message", T: Extension, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Invoice_StatusCode {
    return new Invoice_StatusCode().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Invoice_StatusCode {
    return new Invoice_StatusCode().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Invoice_StatusCode {
    return new Invoice_StatusCode().fromJsonString(jsonString, options);
  }

  static equals(a: Invoice_StatusCode | PlainMessage<Invoice_StatusCode> | undefined, b: Invoice_StatusCode | PlainMessage<Invoice_StatusCode> | undefined): boolean {
    return proto3.util.equals(Invoice_StatusCode, a, b);
  }
}

/**
 * Participant in creation of this Invoice
 *
 * @generated from message google.fhir.r4.core.Invoice.Participant
 */
export class Invoice_Participant extends Message<Invoice_Participant> {
  /**
   * Unique id for inter-element referencing
   *
   * @generated from field: google.fhir.r4.core.String id = 1;
   */
  id?: String;

  /**
   * Additional content defined by implementations
   *
   * @generated from field: repeated google.fhir.r4.core.Extension extension = 2;
   */
  extension: Extension[] = [];

  /**
   * Extensions that cannot be ignored even if unrecognized
   *
   * @generated from field: repeated google.fhir.r4.core.Extension modifier_extension = 3;
   */
  modifierExtension: Extension[] = [];

  /**
   * Type of involvement in creation of this Invoice
   *
   * @generated from field: google.fhir.r4.core.CodeableConcept role = 4;
   */
  role?: CodeableConcept;

  /**
   * Individual who was involved
   *
   * @generated from field: google.fhir.r4.core.Reference actor = 5;
   */
  actor?: Reference;

  constructor(data?: PartialMessage<Invoice_Participant>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.fhir.r4.core.Invoice.Participant";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: String },
    { no: 2, name: "extension", kind: "message", T: Extension, repeated: true },
    { no: 3, name: "modifier_extension", kind: "message", T: Extension, repeated: true },
    { no: 4, name: "role", kind: "message", T: CodeableConcept },
    { no: 5, name: "actor", kind: "message", T: Reference },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Invoice_Participant {
    return new Invoice_Participant().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Invoice_Participant {
    return new Invoice_Participant().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Invoice_Participant {
    return new Invoice_Participant().fromJsonString(jsonString, options);
  }

  static equals(a: Invoice_Participant | PlainMessage<Invoice_Participant> | undefined, b: Invoice_Participant | PlainMessage<Invoice_Participant> | undefined): boolean {
    return proto3.util.equals(Invoice_Participant, a, b);
  }
}

/**
 * Line items of this Invoice
 *
 * @generated from message google.fhir.r4.core.Invoice.LineItem
 */
export class Invoice_LineItem extends Message<Invoice_LineItem> {
  /**
   * Unique id for inter-element referencing
   *
   * @generated from field: google.fhir.r4.core.String id = 1;
   */
  id?: String;

  /**
   * Additional content defined by implementations
   *
   * @generated from field: repeated google.fhir.r4.core.Extension extension = 2;
   */
  extension: Extension[] = [];

  /**
   * Extensions that cannot be ignored even if unrecognized
   *
   * @generated from field: repeated google.fhir.r4.core.Extension modifier_extension = 3;
   */
  modifierExtension: Extension[] = [];

  /**
   * Sequence number of line item
   *
   * @generated from field: google.fhir.r4.core.PositiveInt sequence = 4;
   */
  sequence?: PositiveInt;

  /**
   * @generated from field: google.fhir.r4.core.Invoice.LineItem.ChargeItemX charge_item = 5;
   */
  chargeItem?: Invoice_LineItem_ChargeItemX;

  /**
   * @generated from field: repeated google.fhir.r4.core.Invoice.LineItem.PriceComponent price_component = 6;
   */
  priceComponent: Invoice_LineItem_PriceComponent[] = [];

  constructor(data?: PartialMessage<Invoice_LineItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.fhir.r4.core.Invoice.LineItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: String },
    { no: 2, name: "extension", kind: "message", T: Extension, repeated: true },
    { no: 3, name: "modifier_extension", kind: "message", T: Extension, repeated: true },
    { no: 4, name: "sequence", kind: "message", T: PositiveInt },
    { no: 5, name: "charge_item", kind: "message", T: Invoice_LineItem_ChargeItemX },
    { no: 6, name: "price_component", kind: "message", T: Invoice_LineItem_PriceComponent, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Invoice_LineItem {
    return new Invoice_LineItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Invoice_LineItem {
    return new Invoice_LineItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Invoice_LineItem {
    return new Invoice_LineItem().fromJsonString(jsonString, options);
  }

  static equals(a: Invoice_LineItem | PlainMessage<Invoice_LineItem> | undefined, b: Invoice_LineItem | PlainMessage<Invoice_LineItem> | undefined): boolean {
    return proto3.util.equals(Invoice_LineItem, a, b);
  }
}

/**
 * Reference to ChargeItem containing details of this line item or an inline
 * billing code
 *
 * @generated from message google.fhir.r4.core.Invoice.LineItem.ChargeItemX
 */
export class Invoice_LineItem_ChargeItemX extends Message<Invoice_LineItem_ChargeItemX> {
  /**
   * @generated from oneof google.fhir.r4.core.Invoice.LineItem.ChargeItemX.choice
   */
  choice: {
    /**
     * @generated from field: google.fhir.r4.core.Reference reference = 1;
     */
    value: Reference;
    case: "reference";
  } | {
    /**
     * @generated from field: google.fhir.r4.core.CodeableConcept codeable_concept = 2;
     */
    value: CodeableConcept;
    case: "codeableConcept";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<Invoice_LineItem_ChargeItemX>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.fhir.r4.core.Invoice.LineItem.ChargeItemX";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "reference", kind: "message", T: Reference, oneof: "choice" },
    { no: 2, name: "codeable_concept", kind: "message", T: CodeableConcept, oneof: "choice" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Invoice_LineItem_ChargeItemX {
    return new Invoice_LineItem_ChargeItemX().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Invoice_LineItem_ChargeItemX {
    return new Invoice_LineItem_ChargeItemX().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Invoice_LineItem_ChargeItemX {
    return new Invoice_LineItem_ChargeItemX().fromJsonString(jsonString, options);
  }

  static equals(a: Invoice_LineItem_ChargeItemX | PlainMessage<Invoice_LineItem_ChargeItemX> | undefined, b: Invoice_LineItem_ChargeItemX | PlainMessage<Invoice_LineItem_ChargeItemX> | undefined): boolean {
    return proto3.util.equals(Invoice_LineItem_ChargeItemX, a, b);
  }
}

/**
 * Components of total line item price
 *
 * @generated from message google.fhir.r4.core.Invoice.LineItem.PriceComponent
 */
export class Invoice_LineItem_PriceComponent extends Message<Invoice_LineItem_PriceComponent> {
  /**
   * Unique id for inter-element referencing
   *
   * @generated from field: google.fhir.r4.core.String id = 1;
   */
  id?: String;

  /**
   * Additional content defined by implementations
   *
   * @generated from field: repeated google.fhir.r4.core.Extension extension = 2;
   */
  extension: Extension[] = [];

  /**
   * Extensions that cannot be ignored even if unrecognized
   *
   * @generated from field: repeated google.fhir.r4.core.Extension modifier_extension = 3;
   */
  modifierExtension: Extension[] = [];

  /**
   * @generated from field: google.fhir.r4.core.Invoice.LineItem.PriceComponent.TypeCode type = 4;
   */
  type?: Invoice_LineItem_PriceComponent_TypeCode;

  /**
   * Code identifying the specific component
   *
   * @generated from field: google.fhir.r4.core.CodeableConcept code = 5;
   */
  code?: CodeableConcept;

  /**
   * Factor used for calculating this component
   *
   * @generated from field: google.fhir.r4.core.Decimal factor = 6;
   */
  factor?: Decimal;

  /**
   * Monetary amount associated with this component
   *
   * @generated from field: google.fhir.r4.core.Money amount = 7;
   */
  amount?: Money;

  constructor(data?: PartialMessage<Invoice_LineItem_PriceComponent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.fhir.r4.core.Invoice.LineItem.PriceComponent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: String },
    { no: 2, name: "extension", kind: "message", T: Extension, repeated: true },
    { no: 3, name: "modifier_extension", kind: "message", T: Extension, repeated: true },
    { no: 4, name: "type", kind: "message", T: Invoice_LineItem_PriceComponent_TypeCode },
    { no: 5, name: "code", kind: "message", T: CodeableConcept },
    { no: 6, name: "factor", kind: "message", T: Decimal },
    { no: 7, name: "amount", kind: "message", T: Money },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Invoice_LineItem_PriceComponent {
    return new Invoice_LineItem_PriceComponent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Invoice_LineItem_PriceComponent {
    return new Invoice_LineItem_PriceComponent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Invoice_LineItem_PriceComponent {
    return new Invoice_LineItem_PriceComponent().fromJsonString(jsonString, options);
  }

  static equals(a: Invoice_LineItem_PriceComponent | PlainMessage<Invoice_LineItem_PriceComponent> | undefined, b: Invoice_LineItem_PriceComponent | PlainMessage<Invoice_LineItem_PriceComponent> | undefined): boolean {
    return proto3.util.equals(Invoice_LineItem_PriceComponent, a, b);
  }
}

/**
 * base | surcharge | deduction | discount | tax | informational
 *
 * @generated from message google.fhir.r4.core.Invoice.LineItem.PriceComponent.TypeCode
 */
export class Invoice_LineItem_PriceComponent_TypeCode extends Message<Invoice_LineItem_PriceComponent_TypeCode> {
  /**
   * @generated from field: google.fhir.r4.core.InvoicePriceComponentTypeCode.Value value = 1;
   */
  value = InvoicePriceComponentTypeCode_Value.INVALID_UNINITIALIZED;

  /**
   * @generated from field: google.fhir.r4.core.String id = 2;
   */
  id?: String;

  /**
   * @generated from field: repeated google.fhir.r4.core.Extension extension = 3;
   */
  extension: Extension[] = [];

  constructor(data?: PartialMessage<Invoice_LineItem_PriceComponent_TypeCode>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "google.fhir.r4.core.Invoice.LineItem.PriceComponent.TypeCode";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "value", kind: "enum", T: proto3.getEnumType(InvoicePriceComponentTypeCode_Value) },
    { no: 2, name: "id", kind: "message", T: String },
    { no: 3, name: "extension", kind: "message", T: Extension, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Invoice_LineItem_PriceComponent_TypeCode {
    return new Invoice_LineItem_PriceComponent_TypeCode().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Invoice_LineItem_PriceComponent_TypeCode {
    return new Invoice_LineItem_PriceComponent_TypeCode().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Invoice_LineItem_PriceComponent_TypeCode {
    return new Invoice_LineItem_PriceComponent_TypeCode().fromJsonString(jsonString, options);
  }

  static equals(a: Invoice_LineItem_PriceComponent_TypeCode | PlainMessage<Invoice_LineItem_PriceComponent_TypeCode> | undefined, b: Invoice_LineItem_PriceComponent_TypeCode | PlainMessage<Invoice_LineItem_PriceComponent_TypeCode> | undefined): boolean {
    return proto3.util.equals(Invoice_LineItem_PriceComponent_TypeCode, a, b);
  }
}

