name: Build
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Cache pnpm modules
              uses: actions/cache@v3
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-
            - name: Use Node.js 20.x
              uses: actions/setup-node@v3.4.1
              with:
                  node-version: 20
                  cache: 'pnpm'
            - uses: pnpm/action-setup@v2.2.4
              with:
                  version: latest
                  run_install: true
            - name: Re-run generate to ensure we are up-to-date
              run: pnpm generate
            - name: Build
              run: pnpm build
